jwt.lifetime: 10m

spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://localhost:5432/db_project_employee_handbook
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  security:
    user:
      name: admin
      password: admin