jwt.lifetime: 10m

spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://localhost:5432/db_project_handbook
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher